export const userTypes = {
    USER_REGISTER: "USER_REGISTER",
    USER_LOGIN: "USER_lOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_SIGNPHONE:"USER_SIGNPHONE",
    USER_AUTHENTICATION:"USER_AUTHENTICATION",
    ADD_USERS: "ADD_USERS",
    GET_USER: "GET_USER",    
  };
  